In [1]:
import numpy as np

In [2]:
l=[1,2,3,4,5]

In [3]:
type(l)

list

In [4]:
# we convert list to array with the help of numpy.

In [6]:
a=np.array(l)

In [7]:
a

array([1, 2, 3, 4, 5])

In [8]:
type(a)

numpy.ndarray

In [9]:
# find dimension of array
a.ndim

1

In [12]:
b=np.array([[1,2,3],[4,5,6]])


In [13]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
b.ndim

2

In [15]:
c=np.array([[[1,2,3],
            [4,5,6],
            [7,8,9]]])

In [16]:
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [17]:
c.ndim

3

In [18]:
# matrix dimension start from two dimensions.

In [22]:
l1=[1,2,3,4]

In [32]:
l1

[1, 2, 3, 4]

In [33]:
np.matrix(l)

matrix([[1, 2, 3, 4]])

In [34]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [35]:
b1=np.matrix([[1,2,3],[4,5,6]])

In [36]:
b1

matrix([[1, 2, 3],
        [4, 5, 6]])

In [37]:
np.asanyarray(b1)

matrix([[1, 2, 3],
        [4, 5, 6]])

In [38]:
# matrix is a subclass of array & array is super class of numpy library.
# In asanyarrar we pass matrix then the output is matrix form.
# In asanyarrar we pass list then the output is array.
#  In asanyarrar we pass array then the output is array.

In [93]:
# shallow copy.
a1=[1,2,3,4,5,6]

In [94]:
a1

[1, 2, 3, 4, 5, 6]

In [95]:
a2=np.array(a1)

In [96]:
a2

array([1, 2, 3, 4, 5, 6])

In [97]:
b2=a2

In [86]:
b2

array([1, 2, 3, 4, 5, 6])

In [87]:
b2[2]=30

In [88]:
b2

array([ 1,  2, 30,  4,  5,  6])

In [89]:
a2

array([ 1,  2, 30,  4,  5,  6])

In [90]:
a2[3]=40

In [91]:
a2

array([ 1,  2, 30, 40,  5,  6])

In [92]:
b2

array([ 1,  2, 30, 40,  5,  6])

In [98]:
# deep copy

In [99]:
a3=np.copy(a2)

In [100]:
a3

array([1, 2, 3, 4, 5, 6])

In [101]:
a3[4]=50

In [102]:
a3

array([ 1,  2,  3,  4, 50,  6])

In [103]:
#but a2 is not change.

In [104]:
a2

array([1, 2, 3, 4, 5, 6])

In [105]:
# we use fromfunction generate a dataset.

In [106]:
np.fromfunction(lambda i,j:i==j,(3,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [107]:
# random number generation as array format.

In [108]:
np.random.rand(2,3)

array([[0.03346543, 0.29335666, 0.35066126],
       [0.77258508, 0.0965819 , 0.33484444]])

In [109]:
np.random.rand(2,3,4) # 2: two dimensional array, 3: three rows,4:four columns.

array([[[0.6961303 , 0.05021677, 0.22037428, 0.48009369],
        [0.70753355, 0.03697552, 0.83273144, 0.09262021],
        [0.57143671, 0.55707551, 0.32121369, 0.93165823]],

       [[0.09939983, 0.25229222, 0.8755913 , 0.42626064],
        [0.30967198, 0.28216372, 0.17591041, 0.30840211],
        [0.35309532, 0.81623534, 0.3826848 , 0.94939733]]])

In [110]:
# standard normal distribution.

In [111]:
np.random.randn(3,4,5)

array([[[-0.27338027, -2.09963651, -1.35174621, -0.29599506,
          1.12233478],
        [ 0.35206234, -1.62358526,  0.59353365,  0.63867786,
          1.69109112],
        [-0.75410993, -0.26788339, -0.56657688, -0.07787179,
          1.52925191],
        [ 1.36673042, -0.69121713,  0.24065941, -0.13631615,
          0.17519121]],

       [[ 0.49239213,  0.58841652,  0.46860626,  0.56747992,
          0.04926971],
        [-1.06808113, -0.21757985,  0.44327332,  0.4877567 ,
         -0.19533884],
        [ 1.02008612,  0.84376484,  0.0316882 , -1.3117556 ,
          0.60061698],
        [-0.39596528, -0.27627032, -2.12360201, -0.41570459,
          0.17383636]],

       [[ 0.1712047 ,  1.36334939,  0.5644852 ,  0.74374657,
          0.12117454],
        [ 1.02743092, -0.88914979,  0.76733593, -0.22125756,
         -0.30328255],
        [-2.82356202, -0.29876262,  1.68395732,  1.17539844,
         -0.56868107],
        [ 1.41664885,  0.4572407 , -0.33824665,  0.33726517,
         -0

In [112]:
# integer

In [113]:
np.random.randint(0,10,(3,4,5))

array([[[8, 1, 0, 2, 9],
        [6, 4, 1, 1, 4],
        [2, 7, 2, 4, 5],
        [3, 5, 6, 8, 3]],

       [[2, 6, 3, 7, 7],
        [0, 5, 8, 1, 9],
        [3, 4, 0, 6, 3],
        [5, 8, 8, 7, 3]],

       [[2, 1, 9, 3, 6],
        [6, 1, 3, 4, 0],
        [5, 7, 4, 1, 4],
        [1, 2, 1, 5, 8]]])

In [114]:
# convert array to datafreame & dataframe is a 2d data.

In [115]:
import pandas as pd

In [128]:
d=np.random.randn(3,4)

In [129]:
d

array([[ 1.73499077,  0.41843582, -0.5751314 ,  0.0460519 ],
       [ 0.08957238,  0.75767122,  0.08520709,  1.65060713],
       [-0.9358909 ,  1.13609969, -0.54238751,  1.07320875]])

In [130]:
pd.DataFrame(d)

0         1         2         3
0  1.734991  0.418436 -0.575131  0.046052
1  0.089572  0.757671  0.085207  1.650607
2 -0.935891  1.136100 -0.542388  1.073209

In [131]:
# convert 3d dimension to 2d dimension.

In [132]:
d1=np.random.randint(0,15,(3,4,5))

In [133]:
d1

array([[[11,  2, 12,  5,  0],
        [14,  6, 11,  7,  9],
        [ 7,  6,  4,  4,  0],
        [ 8, 12,  0,  0, 14]],

       [[ 5,  1,  5, 14,  8],
        [ 2,  9, 13, 11,  9],
        [ 5,  4,  3,  3, 13],
        [14,  4,  0,  6,  6]],

       [[ 7,  1,  8,  6,  9],
        [ 5,  8,  5,  1, 13],
        [ 0,  9, 14,  1, 13],
        [ 3, 10, 11,  8, 10]]])

In [134]:
d1.reshape(12,5)

array([[11,  2, 12,  5,  0],
       [14,  6, 11,  7,  9],
       [ 7,  6,  4,  4,  0],
       [ 8, 12,  0,  0, 14],
       [ 5,  1,  5, 14,  8],
       [ 2,  9, 13, 11,  9],
       [ 5,  4,  3,  3, 13],
       [14,  4,  0,  6,  6],
       [ 7,  1,  8,  6,  9],
       [ 5,  8,  5,  1, 13],
       [ 0,  9, 14,  1, 13],
       [ 3, 10, 11,  8, 10]])

In [135]:
d1.reshape(5,12)

array([[11,  2, 12,  5,  0, 14,  6, 11,  7,  9,  7,  6],
       [ 4,  4,  0,  8, 12,  0,  0, 14,  5,  1,  5, 14],
       [ 8,  2,  9, 13, 11,  9,  5,  4,  3,  3, 13, 14],
       [ 4,  0,  6,  6,  7,  1,  8,  6,  9,  5,  8,  5],
       [ 1, 13,  0,  9, 14,  1, 13,  3, 10, 11,  8, 10]])

In [ ]:
# convert array to dataframe.

In [136]:
pd.DataFrame(d1.reshape(5,12))

0   1   2   3   4   5   6   7   8   9   10  11
0  11   2  12   5   0  14   6  11   7   9   7   6
1   4   4   0   8  12   0   0  14   5   1   5  14
2   8   2   9  13  11   9   5   4   3   3  13  14
3   4   0   6   6   7   1   8   6   9   5   8   5
4   1  13   0   9  14   1  13   3  10  11   8  10

In [137]:
range(10)

range(0, 10)

In [140]:
# range function take only integer.
list(range(2,15))

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [144]:
list(range(2.1,15))

TypeError: 'float' object cannot be interpreted as an integer

In [141]:
# arange take floating function.
# arange function update version of range function.

In [145]:
np.arange(2.1,15)

array([ 2.1,  3.1,  4.1,  5.1,  6.1,  7.1,  8.1,  9.1, 10.1, 11.1, 12.1,
       13.1, 14.1])

In [146]:
pd.DataFrame(np.arange(2.1,15))

0
0    2.1
1    3.1
2    4.1
3    5.1
4    6.1
5    7.1
6    8.1
7    9.1
8   10.1
9   11.1
10  12.1
11  13.1
12  14.1

In [148]:
np.arange(3,-1,-.1)

array([ 3.00000000e+00,  2.90000000e+00,  2.80000000e+00,  2.70000000e+00,
        2.60000000e+00,  2.50000000e+00,  2.40000000e+00,  2.30000000e+00,
        2.20000000e+00,  2.10000000e+00,  2.00000000e+00,  1.90000000e+00,
        1.80000000e+00,  1.70000000e+00,  1.60000000e+00,  1.50000000e+00,
        1.40000000e+00,  1.30000000e+00,  1.20000000e+00,  1.10000000e+00,
        1.00000000e+00,  9.00000000e-01,  8.00000000e-01,  7.00000000e-01,
        6.00000000e-01,  5.00000000e-01,  4.00000000e-01,  3.00000000e-01,
        2.00000000e-01,  1.00000000e-01, -2.66453526e-15, -1.00000000e-01,
       -2.00000000e-01, -3.00000000e-01, -4.00000000e-01, -5.00000000e-01,
       -6.00000000e-01, -7.00000000e-01, -8.00000000e-01, -9.00000000e-01])

In [149]:
# linspace function.

In [150]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [152]:
list(np.linspace(1,5,20,retstep=True)) # retstep =true : meaning jump size.

[array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
        2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
        3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
        4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ]),
 0.21052631578947367]

In [153]:
#logspace.

In [156]:
np.logspace(4,5,10)#logarithm value with 10 base.

array([ 10000.        ,  12915.49665015,  16681.005372  ,  21544.34690032,
        27825.59402207,  35938.13663805,  46415.88833613,  59948.42503189,
        77426.36826811, 100000.        ])

In [158]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [159]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [160]:
np.zeros((4,5,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [161]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [162]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [163]:
np.ones((3,5,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [164]:
np.empty((2,3))

array([[0.03346543, 0.29335666, 0.35066126],
       [0.77258508, 0.0965819 , 0.33484444]])

In [165]:
# identity array.

In [167]:
np.eye(4,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [169]:
e=np.random.rand(4,5)

In [170]:
e

array([[0.52062212, 0.6507074 , 0.42830858, 0.12443832, 0.08134484],
       [0.99994577, 0.45172967, 0.91960303, 0.16366028, 0.77698657],
       [0.95285873, 0.94582341, 0.66747883, 0.14304475, 0.39009997],
       [0.54228676, 0.85869402, 0.36701102, 0.52334256, 0.30010962]])

In [171]:
e[1][1]

0.4517296732135866

In [172]:
# matrix multiplication.

In [173]:
m1=np.random.randint(1,10,(3,3))

In [174]:
m1

array([[9, 7, 1],
       [2, 5, 1],
       [8, 7, 1]])

In [175]:
m2=np.random.randint(2,8,(3,3))

In [176]:
m2

array([[4, 6, 2],
       [2, 4, 6],
       [6, 6, 3]])

In [177]:
m1@m2

array([[56, 88, 63],
       [24, 38, 37],
       [52, 82, 61]])

In [178]:
pow(m1,2)

array([[81, 49,  1],
       [ 4, 25,  1],
       [64, 49,  1]], dtype=int32)

In [179]:
np.sqrt(m1)

array([[3.        , 2.64575131, 1.        ],
       [1.41421356, 2.23606798, 1.        ],
       [2.82842712, 2.64575131, 1.        ]])

In [180]:
np.exp(m1)

array([[8.10308393e+03, 1.09663316e+03, 2.71828183e+00],
       [7.38905610e+00, 1.48413159e+02, 2.71828183e+00],
       [2.98095799e+03, 1.09663316e+03, 2.71828183e+00]])

In [181]:
np.log(m2)

array([[1.38629436, 1.79175947, 0.69314718],
       [0.69314718, 1.38629436, 1.79175947],
       [1.79175947, 1.79175947, 1.09861229]])